### ISSUE TITLE
qt webkit doesn't build

### ISSUE THREAD

**Issue by 3nids** [qgis/homebrew-qgisdev#16]
I am not very familiar with this...any idea?
```
Rouzauds-MacBook-Pro:~ denis$ brew install qgis3-dev
==> Installing qgis3-dev from qgis/qgisdev
==> Installing dependencies for qgis/qgisdev/qgis3-dev: osgeo/osgeo4mac/qt5-webkit, sip, pyqt5, qca, qscintilla2, qwt, qwtpolar, gsl, sqlite, expat, proj, postgresql, libpng, libtiff, lzlib, libgeotiff, geos, libxml2, liblwgeom, libspatialite, osgeo/osgeo4mac/gdal2, swig, gdal2, osgeo/osgeo4mac/gdal2-python
==> Installing qgis/qgisdev/qgis3-dev dependency: osgeo/osgeo4mac/qt5-webkit
==> Downloading https://download.qt.io/community_releases/5.7/5.7.0/qtwebkit-opensource-src-5.7.0.tar.gz
Already downloaded: /Users/denis/Library/Caches/Homebrew/qt5-webkit-5.7.0.tar.gz
==> /usr/local/opt/qt5/bin/qmake ../WebKit.pro -config release -spec macx-clang
==> make
Last 15 lines from /Users/denis/Library/Logs/Homebrew/qt5-webkit/02.make:
In file included from /private/tmp/qt5-webkit-20170125-6927-1soov8r/qtwebkit-opensource-src-5.7.0/Source/JavaScriptCore/runtime/JSNotAnObject.cpp:33:
In file included from /private/tmp/qt5-webkit-20170125-6927-1soov8r/qtwebkit-opensource-src-5.7.0/Source/JavaScriptCore/runtime/Operations.h:28:
In file included from /private/tmp/qt5-webkit-20170125-6927-1soov8r/qtwebkit-opensource-src-5.7.0/Source/JavaScriptCore/runtime/JSFunctionInlines.h:29:
In file included from /private/tmp/qt5-webkit-20170125-6927-1soov8r/qtwebkit-opensource-src-5.7.0/Source/JavaScriptCore/runtime/Executable.h:39:
In file included from /private/tmp/qt5-webkit-20170125-6927-1soov8r/qtwebkit-opensource-src-5.7.0/Source/JavaScriptCore/parser/SourceCode.h:32:
/private/tmp/qt5-webkit-20170125-6927-1soov8r/qtwebkit-opensource-src-5.7.0/Source/JavaScriptCore/parser/SourceProvider.h:58:18: warning: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Wundefined-bool-conversion]
            if (!this) // Be defensive in release mode.
                ~^~~~
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make: *** [sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues
```

**Comment by 3nids** [comment]
without-qt-webkit isn't effective, as qt-webkit is still listed as a dependancy (misses a condition there).

**Comment by dakcarto** [comment]
Hi Denis, thanks for reporting. I've bumped the `qt5-webkit` to 5.8.0, since `qt5` upstream is at that version now, and fixed the option. Please `brew update` and try again.

**Comment by dakcarto** [comment]
If it still fails, please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs. Thanks!

**Comment by 3nids** [comment]
Hi Tim, just retried.
`brew install qgis3-dev --only-dependancies` worked fined
Running the cmake script, gave me an error that it couldn't find QtWebkit, no idea why, it should have been installed.
I turned it off in the cmake script, but I suppose there's either still an issue or I did something wrong.
Thanks again for your work!

**Comment by timlinux** [comment]
Great that it works! Kudos go to Larry!

**Comment by 3nids** [comment]
hmmm, really sorry, I mixed up the names....

**Comment by dakcarto** [comment]
Should be fully fixed now that `qgis3-dev` builds against Qt 5.8.0. See known issues in #22.

Reopen if issue still persists.

**Comment by ArrEssJay** [comment]
This is currently broken for me. You previously mention qt 5.8, but homebrew is currently pushing out 5.9.0, whereas osgeo/osgeo4mac/qt5-webkit is at 5.8. Possibly related? Sorry, I'm not that familiar with this.

```
cd /tmp/qgis3-dev-20170613-34472-em5akx/build/python/plugins/db_manager && /tmp/qgis3-dev-20170613-34472-em5akx/scripts/pyuic-wrapper.sh /usr/local/bin/pyuic5 /tmp/qgis3-dev-20170613-34472-em5akx/build/output/lib /tmp/qgis3-dev-20170613-34472-em5akx/build/output/python /usr/local/bin/python3 /tmp/qgis3-dev-20170613-34472-em5akx/python/plugins/db_manager/ui/DlgAddGeometryColumn.ui -o /tmp/qgis3-dev-20170613-34472-em5akx/build/python/plugins/db_manager/ui_DlgAddGeometryColumn.py
Traceback (most recent call last):
  File "/tmp/qgis3-dev-20170613-34472-em5akx/scripts/pyuic-wrapper.py", line 26, in <module>
    import qgis.PyQt.uic.pyuic
  File "/tmp/qgis3-dev-20170613-34472-em5akx/build/output/python/qgis/__init__.py", line 72, in <module>
    from qgis.core import QgsFeature, QgsGeometry
  File "/tmp/qgis3-dev-20170613-34472-em5akx/build/output/python/qgis/core/__init__.py", line 34, in <module>
    from qgis._core import *
ImportError: dlopen(/tmp/qgis3-dev-20170613-34472-em5akx/build/output/python/qgis/_core.so, 2): Symbol not found: __ZN15QQuickFlickable11contentItemEv
  Referenced from: /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Versions/5/QtWebKit
  Expected in: /usr/local/opt/qt5/lib/QtQuick.framework/Versions/5/QtQuick
 in /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Versions/5/QtWebKit
```

**Comment by Gustry** [comment]
@RobDeBagel You should open new ticket.
I think you are right, the current formula is broken as brew is providing QT 5.9

**Comment by m-kuhn** [comment]
See https://github.com/qgis/homebrew-qgisdev/issues/30 and the link to the pull request in there
