### ISSUE TITLE
Launching QGIS 3 dev for the first time error

### ISSUE THREAD

**Issue by arthuragone** [qgis/homebrew-qgisdev#43]
> TypeError: expected str, bytes or os.PathLike object, not NoneType 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py", line 73, in load
    Grass7Utils.grassHelpPath()))
  File "/usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/grass7/Grass7Utils.py", line 506, in grassHelpPath
    localPath = os.path.join(Grass7Utils.path, 'docs/html')
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

OSx
Installed via Homebrew

**Comment by pat-s** [comment]
@arthuragone I also get the same error. However, everything seems to work fine so far. Did you experience any usage issues?

**Comment by dakcarto** [comment]
Hi @arthuragone, thanks for reporting!

This is an upstream issue, and unrelated to the `qgis3-dev` formula.

Please report [upstream](https://issues.qgis.org).
