### ISSUE TITLE
Error: homebrew/science was deprecated

### ISSUE THREAD

**Issue by manelclos** [qgis/homebrew-qgisdev#57]
```
 brew install qgis/qgisdev/qgis3-dev

...

==> Tapping qgis/qgisdev
Cloning into '/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 22 (delta 6), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (22/22), done.
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69:in `<class:Qgis3Dev>'
Please report this to the qgis/qgisdev tap!

Tapped 1 formula (60 files, 148.2KB)
==> Installing qgis3-dev from qgis/qgisdev
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pyqt5-webkit.rb:19:in `<class:Pyqt5Webkit>'
Please report this to the osgeo/osgeo4mac tap!

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pyqt5-webkit.rb:20:in `<class:Pyqt5Webkit>'
Please report this to the osgeo/osgeo4mac tap!

Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
```

**Comment by manelclos** [comment]
Fixed using https://github.com/qgis/homebrew-qgisdev/pull/55
