### ISSUE TITLE
Homebrew making python3 the default python 

### ISSUE THREAD

**Issue by songololo** [qgis/homebrew-qgisdev#64]
Homebrew recently made `python3` the default `python` per [this blog post](https://brew.sh/2018/01/19/homebrew-1.5.0/), which means that references to `python3` should become `python` and `pip3` should become `pip`.

Any references to Python v2 should now explicitly reference `python2`.

**Comment by luispuerto** [comment]
this have changed and now `python` is again `python2`

**Comment by geoHeil** [comment]
here is the exact error message
```
brew install qgis/qgisdev/qgis3-dev
Error: Calling 'depends_on :python3' is disabled!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69:in `<class:Qgis3Dev>'
Please report this to the qgis/qgisdev tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/qgis/homebrew-qgisdev/issues
```

how can I fix this? currently the installation of qgis3 via home-brew fails for me.

**Comment by geoHeil** [comment]
duplicate of https://github.com/qgis/homebrew-qgisdev/issues/58

**Comment by luispuerto** [comment]
AFK that is just a warning, so if it isn't building it's posible that other thing is the reason. To remove that warning you have to do what it's asking for, change `depends_on :python3` for `depends_on "python". 

I've was able to build myself a couple of weeks ago with this modify version of the formula. 

https://github.com/luisspuerto/homebrew-qgisdev/blob/matplotlib-fix%2Bpython/Formula/qgis3-dev.rb

It builds 3.0.1

**Comment by geoHeil** [comment]
@luisspuerto https://github.com/qgis/homebrew-qgisdev/pull/61/files already did this. However, the test cases fail

**Comment by luispuerto** [comment]
@geoHeil there are more things to change. I really think that isn't the reason because your formula isn't building since that is just a warning as far as I know. 

You can make a diff with my formula, but I think you have to change also 

`depends_on "homebrew/science/matplotlib"` or `depends_on "brewsci/science/matplotlib"` (depents on the version of your original formula) to `depends_on "brewsci/bio/matplotlib"`

As I said I was able to build like a couple of weeks ago. I also changed: 

```ruby
url "https://github.com/qgis/QGIS.git", :branch => "master"
  version "2.99"
```
to 
```ruby 
url "https://github.com/qgis/QGIS.git", :branch => "release-3_0"
  version "3.0.1"
```
to build the stable version. 

Perhaps some of the dependencies has changed or something (GDAL2 has been update) and there is something more. Check your warnings and errors.

**Comment by geoHeil** [comment]
Strange - when editing the `depends_on` - now I see:
```
calling 'depends_on :python' is disabled!
Use 'depends_on "python@2"' instead.
```
Is there a way to turn on debug mode which gives a more verbose error message?

Also, (it no longer seems to be) a mere warning but a real error.

**Comment by luispuerto** [comment]
Perhaps you have to change in more than one place... recheck the formula. Usually when that warning showed up tells you in which line is.

**Comment by geoHeil** [comment]
After a diff I followed along with what you propose and use https://gist.github.com/geoHeil/19dffb7cd526655b2e70bae84633e217, however, the error remains.

```
Use 'depends_on "python@2"' instead.
/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69:in `<class:Qgis3Dev>'

```
which in return refers to line 69, which is:
`  depends_on :python
`

**Comment by geoHeil** [comment]
When applying the suggested fix of `@2`

```
Error: qgis/qgisdev/qgis3-dev: /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69: `@2' is not allowed as an instance variable name
/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69: syntax error, unexpected end-of-input, expecting keyword_end
  depends_on :python@2
```
it again fails.

**Comment by geoHeil** [comment]
I found the error: 
`"python"` must be written with quotes.
This gets me a bit further:
```
brew install qgis/qgisdev/qgis3-dev
==> Installing qgis3-dev from qgis/qgisdev
==> Tapping brewsci/bio
Cloning into '/usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio'...
remote: Counting objects: 145, done.
remote: Compressing objects: 100% (143/143), done.
remote: Total 145 (delta 2), reused 110 (delta 1), pack-reused 0
Receiving objects: 100% (145/145), 100.28 KiB | 1.01 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Tapped 131 formulae (164 files, 317.0KB)
qt5-webkit: Must be built with `brew install --no-sandbox ...`, or install steps will fail.
Error: An unsatisfied requirement failed this build.
```

**Comment by luispuerto** [comment]
remove the `:` on `depends_on :python` and put in quotes that was what it was telling you from the beginning...  😉

**Comment by geoHeil** [comment]
After installing the missing dependency
`brew install --no-sandbox qt5-webkit`

Installation again fails:
```
brew install qgis/qgisdev/qgis3-dev
==> Installing qgis3-dev from qgis/qgisdev
qt5-webkit: Must be built with `brew install --no-sandbox ...`, or install steps will fail.
Error: An unsatisfied requirement failed this build.
```

**Comment by luispuerto** [comment]
in other words... that line is 

```ruby 
depends_on "python"
```

**Comment by geoHeil** [comment]
@luisspuerto thanks for your suggestion. Indeed, that works - partially. I am now stuck with qt5-webkit.

**Comment by luispuerto** [comment]
again read.... you have to build with qgis-dev with the

```sh 
brew install --no-sandbox qgis3-dev --whatever-aditional-flags-you-want-to-put-here
```

I parse in my in case: 

```sh 
brew install --no-sandbox qgis3-dev --with-grass --with-saga-gis-lts
```

**Comment by luispuerto** [comment]
PS/ man I really think you should read slower and more calm the messages 🤓. Don't worry... everyone can get really excited about installing QGIS. 😂

**Comment by geoHeil** [comment]
Thanks a lot. I am still not fully there.

```
 brew install --no-sandbox qgis/qgisdev/qgis3-dev
==> Installing qgis3-dev from qgis/qgisdev
==> Cloning https://github.com/qgis/QGIS.git
Updating /Users/geoheil/Library/Caches/Homebrew/qgis3-dev--git
==> Checking out branch master
==> /usr/local/bin/pip3 install --user future psycopg2 python-dateutil httplib2 pytz six nose2 pygments jinja2 pyyaml requests owslib
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis3-d
Last 15 lines from /Users/geoheil/Library/Logs/Homebrew/qgis3-dev/02.cmake:
--   skipping QCA OpenSSL plugin C++ check
-- Found Libtasn1: /usr/local/include
-- Pedantic compiler settings enabled
-- Debug output enabled
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /usr/local/bin/python3)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPythonInterp.cmake:155 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:696 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/qgis3-dev-20180411-65559-rawjfr/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/qgis/homebrew-qgisdev/issues

These open issues may also help:
Update qgis3-dev.rb https://github.com/qgis/homebrew-qgisdev/pull/63
Update qgis3-dev.rb https://github.com/qgis/homebrew-qgisdev/pull/61
Python 3.6.0 upgrade breaks existing qgis3-dev https://github.com/qgis/homebrew-qgisdev/issues/11

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

However, the latest version of the CLI / Xcode 9.3 (9E145 ) is already installed.

**Comment by geoHeil** [comment]
https://github.com/qgis/homebrew-qgisdev/issues/2 seems to be related, however `PYTHONPATH ` is not set on my machine.

**Comment by luispuerto** [comment]
> However, the latest version of the CLI / Xcode 9.3 (9E145 ) is already installed.

Why do you way that? it's asking you for the last version of `PythonInterp`

```
Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /usr/local/bin/python3)
```

do you have python3 installed with homebrew?

**Comment by geoHeil** [comment]
I have installed:
```
brew ls |grep python
gdal2-python
python
python@2
wxpython
brew info python
python: stable 3.6.5
```

**Comment by luispuerto** [comment]
perhaps you have to unlink and link again. 

```
brew unlink python 
brew link python 
```

Python has been messy lately. 

Check also in your terminal 

```sh 
python --version 
ptyhon3 --version
```

**Comment by geoHeil** [comment]
brew links python (which is version `3.6.5`) to `python3`. python --version returns python `2.x.`

**Comment by luispuerto** [comment]
remember that in homebrew `python` is `python3`, but in your terminal `python` should point to `python2` and `python3` to `python3` (obviously).

**Comment by geoHeil** [comment]
so 
```
> $ python --version
Python 2.7.14

geoheil@eduroam-078-104-029-050 ~                                                                                           [17:26:00]
> $ python3 --version
Python 3.6.5
```
is supposed to be correct for qgis3?

**Comment by luispuerto** [comment]
yes

**Comment by geoHeil** [comment]
so how can I then fix:
```
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /usr/local/bin/python3)
```

**Comment by luispuerto** [comment]
I really don't know what is exactly the problem here... clearly a python one 🐍. 

If you have python and python3 installed with home brew I would reinstall both of them and unlink and link again. 

For some reason the formula isn't able to find python 3 in your machine.

**Comment by geoHeil** [comment]
I tried this already and reinstalled both versions - but this does not help.

**Comment by geoHeil** [comment]
I removed both` python@2` and `python` and from a clean system installed `brew install --no-sandbox qgis/qgisdev/qgis3-dev --with-grass --with-r` which successively installs required dependencies. This installs nicely, however NOT qgis_dev!!

When running this command again, it tries to install qgis_dev, but fails to do so again due to the same error:
```
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /usr/local/bin/python3)
```

**Comment by luispuerto** [comment]
As you referenced earlier I think it's related to #2. There the problem was that the `CMAKELISTS.TXT`file got stuck with python2. You have to delete it. I don't know where it's exactly but I think it's in the cache folder. I would delete the entire cache folder for qgis3-dev in `~/Library/Caches/Homebrew`
In other words, you had problems with python, tried to build, now you fixed, but the build config still has the old config. Delete the build folder and start building from scratch.

**Comment by luispuerto** [comment]
I think the file is located in `~/Library/Caches/Homebrew/qgis3-dev--git/CMakeLists.txt`

**Comment by luispuerto** [comment]
probably the best way is deleting the entire `~/Library/Caches/Homebrew/qgis3-dev--git/` folder so homebrew download it again.

**Comment by geoHeil** [comment]
Unfortunately, this does not help.

**Comment by geoHeil** [comment]
When running in verbose mode:

`brew install -v --no-sandbox qgis/qgisdev/qgis3-dev --with-grass --with-r`
the output is:
```
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis3-dev/3.0.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=/usr/local/opt/qt;/usr/local/opt/qt5-webkit;/usr/local/opt/qscintilla2;/usr/local/opt/qwt;/usr/local/opt/qwtpolar;/usr/local/opt/qca;/usr/local/opt/gdal2;/usr/local/opt/gsl;/usr/local/opt/geos;/usr/local/opt/proj;/usr/local/opt/libspatialite;/usr/local/opt/spatialindex;/usr/local/opt/expat;/usr/local/opt/sqlite;/usr/local/opt/libzip;/usr/local/opt/flex;/usr/local/opt/bison;/usr/local/opt/fcgi -DENABLE_TESTS=FALSE -DENABLE_MODELTEST=FALSE -DQGIS_MACAPP_BUNDLE=0 -DQGIS_MACAPP_INSTALL_DEV=FALSE -DWITH_QWTPOLAR=TRUE -DWITH_INTERNAL_QWTPOLAR=FALSE -DWITH_ASTYLE=FALSE -DWITH_QSCIAPI=TRUE -DWITH_STAGED_PLUGINS=TRUE -DWITH_GRASS=FALSE -DWITH_CUSTOM_WIDGETS=TRUE -DWITH_QTWEBKIT=TRUE -DGDAL_LIBRARY=/usr/local/opt/gdal2/lib/libgdal.dylib -DGEOS_LIBRARY=/usr/local/opt/geos/lib/libgeos_c.dylib -DGSL_CONFIG=/usr/local/opt/gsl/bin/gsl-config -DGSL_INCLUDE_DIR=/usr/local/opt/gsl/include -DGSL_LIBRARIES='-L/usr/local/opt/gsl/lib -lgsl -lgslcblas' -DWITH_SERVER=TRUE -DPOSTGRES_CONFIG=/usr/local/opt/postgresql/bin/pg_config -DWITH_GRASS7=TRUE -DGRASS_PREFIX7='/usr/local/opt/grass7/grass-base' -DWITH_GLOBE=FALSE -DWITH_ORACLE=FALSE -DWITH_QSPATIALITE=FALSE -DWITH_APIDOC=FALSE -DWITH_3D=FALSE -DCLANG_TIDY_EXE= ..
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- QGIS version: 3.1.0 Master (30100)
-- Found GRASS 7: /usr/local/opt/grass7/grass-base (7.2.2, off_t size = )
-- Looking for openpty
-- Looking for openpty - found
-- Looking for proj_info in /usr/local/opt/proj/lib/libproj.dylib
-- Looking for proj_info in /usr/local/opt/proj/lib/libproj.dylib - found
-- Found Proj: /usr/local/opt/proj/lib/libproj.dylib
-- Found GEOS: /usr/local/opt/geos/lib/libgeos_c.dylib (3.6.2)
-- Found GDAL: /usr/local/opt/gdal2/lib/libgdal.dylib (2.2.4)
-- Found Expat: /usr/local/opt/expat/lib/libexpat.dylib
-- Found Spatialindex: /usr/local/opt/spatialindex/lib/libspatialindex.dylib
-- Found Qwt: /usr/local/opt/qwt/lib/qwt.framework (6.1.3)
-- Found libzip: /usr/local/opt/libzip/lib/libzip.dylib
-- Found Sqlite3: /usr/local/opt/sqlite/lib/libsqlite3.dylib
-- Found PostgreSQL: /usr/local/lib/libpq.dylib
-- Found SpatiaLite: /usr/local/opt/libspatialite/lib/libspatialite.dylib
-- Looking for gaiaStatisticsInvalidate in /usr/local/opt/libspatialite/lib/libspatialite.dylib
-- Looking for gaiaStatisticsInvalidate in /usr/local/opt/libspatialite/lib/libspatialite.dylib - found
-- Qt WebKit support enabled
-- Found Qt version: 5.10.1
-- Found QScintilla2: /usr/local/opt/qscintilla2/lib/libqscintilla2_qt5.dylib (2.10.4)
-- Found QtKeychain: /usr/local/lib/libqt5keychain.dylib
-- Found QCA: /usr/local/opt/qca/lib/qca-qt5.framework (2.1.3)
-- QtCore/QCA include/lib variables missing or CMake is cross-compiling,
--   skipping QCA OpenSSL plugin C++ check
-- Found Libtasn1: /usr/local/include
-- Pedantic compiler settings enabled
-- Debug output enabled
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /usr/local/bin/python3)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPythonInterp.cmake:155 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:696 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/qgis3-dev-20180414-6961-20zse3/build/CMakeFiles/CMakeOutput.log".

==> Formula
Tap: qgis/qgisdev
Path: /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb
==> Configuration
HOMEBREW_VERSION: 1.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: e3cd9c972f55e9953830f98b4b64eb4ba10727b1
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2ff018af999d2cab2fde433b585f28a76b873625
Core tap last commit: 3 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10, 1.8.0_162, 1.8.0_131
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.3
XQuartz: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CXXFLAGS: -isystem /usr/local/Cellar/grass7/7.2.2/grass-base/include
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/bison:/usr/local/opt/flex:/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/qt:/usr/local/opt/qt5-webkit:/usr/local/opt/expat:/usr/local/opt/libxml2:/usr/local/opt/gdal2:/usr/local/opt/gdal2-python:/usr/local/opt/gettext:/usr/local/opt/libffi:/usr/local/opt/openblas:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/apache2:/opt/X11/include:/opt/X11/include/freetype2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /opt/X11/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks:/usr/local/opt/qt/Frameworks:/usr/local/opt/qt5-webkit/Frameworks:/usr/local/opt/python@2/Frameworks:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/qt5-webkit/lib/pkgconfig:/usr/local/opt/python@2/lib/pkgconfig:/usr/local/opt/qca/lib/pkgconfig:/usr/local/opt/gsl/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/spatialindex/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/postgresql/lib/pkgconfig:/usr/local/opt/libzip/lib/pkgconfig:/usr/local/opt/libtasn1/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/json-c/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/freexl/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libspatialite/lib/pkgconfig:/usr/local/opt/gdal2/lib/pkgconfig:/usr/local/opt/unixodbc/lib/pkgconfig:/usr/local/opt/mpfr/lib/pkgconfig:/usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/fftw/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/little-cms2/lib/pkgconfig:/usr/local/opt/openblas/lib/pkgconfig:/usr/local/opt/r/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
ACLOCAL_PATH: /usr/local/opt/bison/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal:/opt/X11/share/aclocal
PATH: /usr/local/Cellar/qgis3-dev/3.0.1/libexec/python/bin:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cmake/bin:/usr/local/opt/ninja/bin:/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python/bin:/usr/local/opt/qt/bin:/usr/local/opt/python@2/bin:/usr/local/opt/sip/bin:/usr/local/opt/pyqt/bin:/usr/local/opt/qca/bin:/usr/local/opt/gsl/bin:/usr/local/opt/expat/bin:/usr/local/opt/proj/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/numpy/bin:/usr/local/opt/fcgi/bin:/usr/local/opt/postgresql/bin:/usr/local/opt/libzip/bin:/usr/local/opt/libtasn1/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/giflib/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/libgeotiff/bin:/usr/local/opt/geos/bin:/usr/local/opt/pcre/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/gdal2/bin:/usr/local/opt/gdal2-python/bin:/usr/local/opt/gettext/bin:/usr/local/opt/lbzip2/bin:/usr/local/opt/libtool/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/gcc/bin:/usr/local/opt/fftw/bin:/usr/local/opt/wxmac/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/glib/bin:/usr/local/opt/cairo/bin:/usr/local/opt/little-cms2/bin:/usr/local/opt/ghostscript/bin:/usr/local/opt/grass7/bin:/usr/local/opt/r/bin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: qgis/qgisdev/qgis3-dev 3.0.1 did not build
Logs:
     /Users/geoheil/Library/Logs/Homebrew/qgis3-dev/02.cmake.cc
     /Users/geoheil/Library/Logs/Homebrew/qgis3-dev/00.options.out
     /Users/geoheil/Library/Logs/Homebrew/qgis3-dev/01.pip3
     /Users/geoheil/Library/Logs/Homebrew/qgis3-dev/02.cmake
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/qgis/homebrew-qgisdev/issues

These open issues may also help:
Update qgis3-dev.rb https://github.com/qgis/homebrew-qgisdev/pull/63
Update qgis3-dev.rb https://github.com/qgis/homebrew-qgisdev/pull/61
Python 3.6.0 upgrade breaks existing qgis3-dev https://github.com/qgis/homebrew-qgisdev/issues/11

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

**Comment by geoHeil** [comment]
Maybe https://stackoverflow.com/questions/7660001/cmake-finds-wrong-python-libs is helpful to fix the problem.

**Comment by geoHeil** [comment]
When trying to reproduce the error in a minimal example like:
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.0.0)
FIND_PACKAGE(PythonInterp 3 REQUIRED)
```
and executing `cmake <<my_folder>>` The output interestingly is:
```
Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.6.5", minimum required is "3")
```
which leads me to believe that some of the prefix paths passed by hombrew cause a problem.

When using the `prefix_path`from the logs:
```
cmake <<my_folder>>/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt;/usr/local/opt/qt5-webkit;/usr/local/opt/qscintilla2;/usr/local/opt/qwt;/usr/local/opt/qwtpolar;/usr/local/opt/qca;/usr/local/opt/gdal2;/usr/local/opt/gsl;/usr/local/opt/geos;/usr/local/opt/proj;/usr/local/opt/libspatialite;/usr/local/opt/spatialindex;/usr/local/opt/expat;/usr/local/opt/sqlite;/usr/local/opt/libzip;/usr/local/opt/flex;/usr/local/opt/bison;/usr/local/opt/fcgi
```
the output remains `3.6.5`
Unfortunately, homebrew output was truncated - so I am not sure if further options are passed.

**Comment by geoHeil** [comment]
Is there a way to get the full log of variables passed to cmake?

**Comment by fjperini** [comment]
![QGIS](https://raw.githubusercontent.com/fjperini/homebrew-qgisdev/matplotlib-fix%2Bpython/screenshot.png "QGIS")

I already made a pull request to inform the changes that must be made.

Click to see how to install [QGIS 3.2](https://github.com/fjperini/homebrew-qgisdev/blob/matplotlib-fix%2Bpython/INSTALL.md)
