### ISSUE TITLE
cannot tap qgis/qgisdev

### ISSUE THREAD

**Issue by xg1990** [qgis/homebrew-qgisdev#68]
```
 $ brew tap qgis/qgisdev
==> Tapping qgis/qgisdev
Cloning into '/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 22 (delta 6), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (22/22), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb
Calling 'depends_on :python3' is disabled!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69:in `<class:Qgis3Dev>'
Please report this to the qgis/qgisdev tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap qgis/qgisdev: invalid syntax in tap!
```

more detail:

 ```
$ brew tap qgis/qgisdev --debug
==> Tapping qgis/qgisdev
Cloning into '/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 22 (delta 6), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (22/22), done.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb
Calling 'depends_on :python3' is disabled!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb:69:in `<class:Qgis3Dev>'
Please report this to the qgis/qgisdev tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap qgis/qgisdev: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:270:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:50:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by fjperini** [comment]
![QGIS](https://raw.githubusercontent.com/fjperini/homebrew-qgisdev/matplotlib-fix%2Bpython/screenshot.png "QGIS")

I already made a pull request to inform the changes that must be made.

Click to see how to install [QGIS 3.2](https://github.com/fjperini/homebrew-qgisdev/blob/matplotlib-fix%2Bpython/INSTALL.md)

**Comment by ozak** [comment]
Related to #58.

**Comment by Gwang-Jin** [comment]
I have the same problem

````
$ brew tap qgis/qgisdev --debug
==> Tapping qgis/qgisdev
Cloning into '/usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 22 (delta 6), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (22/22), done.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/qgis/homebrew-qgisdev/Formula/qgis3-dev.rb
qgis3-dev: Unsupported special dependency :python3
Error: Cannot tap qgis/qgisdev: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:270:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:50:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
````
